### ISSUE TITLE
你的工作非常棒，非常有创造性，为你点赞。

### ISSUE THREAD

**Issue by sunjunlishi** [jiangnanboy/table_structure_recognition#2]
我们想找到表格的边界是个非常困难的事情。因为线太细了，提取特征是个比较困难的事情。
我曾考虑采用YOLO的算法检测，效果不佳。你这个算法是更好的。

所以我在想，先用你的这个算法检测线，把线加颜色加粗，然后再用yolo去检测cell是个就是个可以实现美妙的事情。

**Comment by nissansz** [comment]
怎么转onnx，怎么用？

**Comment by jiangnanboy** [comment]
可自行转onnx，用onnx进行推理可行

**Comment by nissansz** [comment]
没有环境转，可以帮忙转？然后发onnx推理代码？









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: AI  ***@***.***>
 

 
 发送时间: 2024-10-09 22:34:10
 

 
 收件人:jiangnanboy/table_structure_recognition ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Comment ***@***.***> 

 
 主题: Re: [jiangnanboy/table_structure_recognition] 你的工作非常棒，非常有创造性，为你点赞。 (Issue #2)
 





 可自行转onnx，用onnx进行推理可行

**Comment by jiangnanboy** [comment]
用onnx转一下就ok了

**Comment by nissansz** [comment]
不会转，可以帮忙转一下试试？









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: AI  ***@***.***>
 

 
 发送时间: 2024-10-14 20:47:22
 

 
 收件人:jiangnanboy/table_structure_recognition ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Comment ***@***.***> 

 
 主题: Re: [jiangnanboy/table_structure_recognition] 你的工作非常棒，非常有创造性，为你点赞。 (Issue #2)
 





 用onnx转一下就ok了

**Comment by jiangnanboy** [comment]
转后，需要做后处理。这个需要写后处理程序的。

**Comment by nissansz** [comment]
怎么写？









--------------------------------------------------------------------------------





------------------ 原始邮件 ------------------




 
 发件人: AI  ***@***.***>
 

 
 发送时间: 2024-10-14 22:42:17
 

 
 收件人:jiangnanboy/table_structure_recognition ***@***.***> 

 
 抄送:nissanjp ***@***.***>,Comment ***@***.***> 

 
 主题: Re: [jiangnanboy/table_structure_recognition] 你的工作非常棒，非常有创造性，为你点赞。 (Issue #2)
 





 转后，需要做后处理。这个需要写后处理程序的。
